### ISSUE TITLE
Not an Issue but a question on how to config works EXCATLY

### ISSUE THREAD

**Issue by VanilaBOI** [Electric131/IsThisTheWayICame#2]
I'm gonna say how I understand them and I hope you can tell me if I'm right or not.

Fake Chance: This I thought was straight forward and just determents If anyone at anytime enters a Fire Exit, if they get sent to a fake(meaning me and my friend can go in and I go to the right one and he doesn't)

Change on Use: You say the destination changes whenever a player uses the exterior Fire exit. So when its set to true It's rerolled every time I or some else enters(meaning if it's set to false it either sends all of us to the wrong one or to the right one)

Change on Use Chance: Is this the chance you have on switching the destination?

I am mainly confused because I have my config as Fake Chance 33, Change on Use false, Change on Use Chance 25
And I only get teleported to the fake one?

**Comment by Electric131** [comment]
Better explanations:

Fake Chance: The percent chance that the destination of the door is moved to a mimic (IF AVAILABLE), otherwise sticks with the original door.

Change on Use: If true, the destination is re-rolled (not necessarily changed) based on the fake chance. If false, this part is skipped and the destination never changes from the one it chose when the map was generated.

Change on Use Chance: Percent chance that the destination is re-rolled whenever a player goes through the exterior fire exit.

The last part is simply you rolled the 33% chance to spawn at a mimic, and based on change on use false, the destination will never change.
